"""
Exports the frozen, ImageNet-pretrained ResNet18 used for gem-presence
detection to ONNX, and precomputes the reference gem embeddings
("database") alongside it -- so `capture_pipeline.py` only ever needs
`onnxruntime` (a light, inference-only dependency) at capture time, not
the full `torch`/`torchvision` stack. See AI_RAMBLINGS.md's "Embeddings
for gem PRESENCE" section for the real validation numbers (0 of 62 real
non-gem samples exceeded the real gem floor) and why this replaced the
pixel-correlation approach.

`torch`/`torchvision`/`onnx`/`onnxscript` are needed to RUN this script
(a one-time or occasional dev-side step, not something end users need)
-- not to USE its output. Only `onnxruntime` is a production
dependency; see requirements.txt.

Usage:
    python export_gem_embedding_model.py

Writes to assets/models/:
    gem_embedding_resnet18.onnx       -- the model graph
    gem_embedding_resnet18.onnx.data  -- the model weights (~45MB;
                                          torch's exporter writes graph
                                          and weights as separate files,
                                          both required to load the model)
    gem_reference_embeddings.json     -- {gem name: 512-d embedding} for
                                          every file in assets/gems/,
                                          precomputed once so production
                                          never re-embeds the references
"""

import json
import os

import numpy as np
import torch
import torchvision
from torchvision import transforms
from PIL import Image

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(TOOLS_DIR)

GEMS_DIR = os.path.join(PROJECT_ROOT, "assets", "gems")
MODELS_DIR = os.path.join(PROJECT_ROOT, "assets", "models")
ONNX_PATH = os.path.join(MODELS_DIR, "gem_embedding_resnet18.onnx")
REFERENCE_EMBEDDINGS_PATH = os.path.join(MODELS_DIR, "gem_reference_embeddings.json")

# Same preprocessing used for the real validation in AI_RAMBLINGS.md --
# standard ImageNet normalization, resized directly to the network's
# native 224x224 input (no crop margin, since these are already tight
# single-item icon crops, not photos with irrelevant surrounding content).
PREPROCESS = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])


def build_model() -> torch.nn.Module:
    """Frozen ImageNet ResNet18 with its final classifier stripped, so
    the output is the 512-d penultimate-layer feature vector rather
    than a 1000-way ImageNet class prediction -- the actual "embedding"
    compared by cosine similarity. No fine-tuning: this is the
    off-the-shelf pretrained network, used as-is."""
    weights = torchvision.models.ResNet18_Weights.IMAGENET1K_V1
    model = torchvision.models.resnet18(weights=weights)
    model.fc = torch.nn.Identity()
    model.eval()
    return model


def embed(model: torch.nn.Module, image_path: str) -> np.ndarray:
    img = Image.open(image_path).convert("RGB")
    with torch.no_grad():
        vec = model(PREPROCESS(img).unsqueeze(0))[0].numpy()
    return vec / np.linalg.norm(vec)


def export():
    os.makedirs(MODELS_DIR, exist_ok=True)
    model = build_model()

    dummy = torch.randn(1, 3, 224, 224)
    torch.onnx.export(
        model, dummy, ONNX_PATH,
        input_names=["input"], output_names=["embedding"],
        dynamic_axes={"input": {0: "batch"}, "embedding": {0: "batch"}},
    )
    onnx_size_mb = os.path.getsize(ONNX_PATH) / 1e6
    data_path = ONNX_PATH + ".data"
    data_size_mb = os.path.getsize(data_path) / 1e6 if os.path.isfile(data_path) else 0.0
    print(f"Exported {ONNX_PATH} ({onnx_size_mb:.2f} MB graph)")
    if data_size_mb:
        print(f"  + {data_path} ({data_size_mb:.1f} MB weights -- both files required)")

    gem_paths = sorted(
        p for p in os.listdir(GEMS_DIR) if p.lower().endswith(".png")
    )
    references = {}
    for fname in gem_paths:
        name = os.path.splitext(fname)[0]
        vec = embed(model, os.path.join(GEMS_DIR, fname))
        references[name] = vec.tolist()

    with open(REFERENCE_EMBEDDINGS_PATH, "w", encoding="utf-8", newline="\n") as f:
        json.dump({
            "note": "AUTOGENERATED FILE -- DO NOT MODIFY. Regenerate with "
                     "export_gem_embedding_model.py if assets/gems/ changes.",
            "embeddings": references,
        }, f, indent=2)
    print(f"Wrote {REFERENCE_EMBEDDINGS_PATH} ({len(references)} reference gems)")


if __name__ == "__main__":
    export()
