"""
Precomputes embeddings for every labeled support-icon reference in
assets/harvested_supports/ (built by harvest_support_icons.py from real
warrant.txt ground truth), so capture_pipeline.py's live support
matching never re-embeds 100+ reference images at capture time.

Unlike export_gem_embedding_model.py, this does NOT need torch --
it reuses the ONNX model that tool already exported
(assets/models/gem_embedding_resnet18.onnx, a generic ImageNet feature
extractor, not gem-specific) via onnxruntime alone, the same way
tools/match_support_icon.py already does. Run this any time
assets/harvested_supports/ changes (i.e. after re-running
harvest_support_icons.py with new captures).

Usage:
    python export_support_reference_embeddings.py

Must run from the project root (imports capture_pipeline, which
resolves its own asset paths relative to cwd).

Reads: assets/harvested_supports/ (top-level reference PNGs only --
    excludes unlabeled_<hash>.png placeholders and the variants/
    subfolder, which hold near-duplicate noise of an already-covered
    identity, not additional identities)
Writes: assets/models/support_reference_embeddings.json
"""
import json
import os
import sys

PROJECT_ROOT = os.getcwd()
sys.path.insert(0, PROJECT_ROOT)

from PIL import Image
import capture_pipeline as cp

HARVESTED_DIR = os.path.join(PROJECT_ROOT, "assets", "harvested_supports")
OUTPUT_PATH = os.path.join(PROJECT_ROOT, "assets", "models", "support_reference_embeddings.json")


def export():
    session = cp._load_gem_embedding_session()
    if session is None:
        print(f"No embedding model found at {cp.GEM_EMBEDDING_MODEL_PATH} -- "
              f"run export_gem_embedding_model.py first.")
        return

    references = {}
    for fname in sorted(os.listdir(HARVESTED_DIR)):
        if not fname.lower().endswith(".png"):
            continue
        visual_key = os.path.splitext(fname)[0]
        if visual_key.startswith("unlabeled_"):
            continue  # a genuinely unresolved cluster (no ground truth, no tier) --
            # not a real (icon, tier) identity, see match_support_icon.py's own
            # docstring for why including these only adds confusable noise
        crop = Image.open(os.path.join(HARVESTED_DIR, fname))
        vec = cp._embed_crop(crop, session)
        references[visual_key] = vec.tolist()

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        json.dump({
            "note": "AUTOGENERATED FILE -- DO NOT MODIFY. Regenerate with "
                     "export_support_reference_embeddings.py after re-running "
                     "harvest_support_icons.py.",
            "embeddings": references,
        }, f, indent=2)
    print(f"Wrote {OUTPUT_PATH} ({len(references)} reference (icon, tier) keys)")


if __name__ == "__main__":
    export()
