"""
Regenerates assets/support_icon_collisions.md from definitions/supports.json
and definitions/supports_by_skills.json -- the enumerable, data-derived
answer to "which supports render pixel-identical, and does that ever
actually matter." See AI_RAMBLINGS.md's "Icon-collision-by-family report"
section for the original investigation and the correction that led to
this script (a family-based grouping over-counted "collisions" that were
really just two different skills each offering one unique Gilded support).

A render group is every support sharing one (icon, tier_roman) --
exactly the unit `_support_visual_key_to_names()` in capture_pipeline.py
groups by, i.e. the actual resolution unit `match_support_icon()` can
never split further on its own.

Two outcomes per render group with more than one member:
  - Cross-skill only: the members never both appear in any one skill's
    own `PossibleSupports` -- knowing which skill produced the crop is
    always enough to resolve identity, so this is not a real ambiguity.
  - Same-skill collision: at least one skill's own `PossibleSupports`
    offers two or more members of the group -- no image-based method
    can do better than reporting "X or Y" for that skill.

Usage:
    python generate_support_collision_report.py

Reads: definitions/supports.json, definitions/supports_by_skills.json
Writes: assets/support_icon_collisions.md
"""
import json
import os

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(TOOLS_DIR)
SUPPORTS_PATH = os.path.join(PROJECT_ROOT, "definitions", "supports.json")
SUPPORTS_BY_SKILLS_PATH = os.path.join(PROJECT_ROOT, "definitions", "supports_by_skills.json")
OUTPUT_PATH = os.path.join(PROJECT_ROOT, "assets", "support_icon_collisions.md")


def generate():
    with open(SUPPORTS_PATH, encoding="utf-8") as f:
        supports = json.load(f)["supports"]
    with open(SUPPORTS_BY_SKILLS_PATH, encoding="utf-8") as f:
        skills = json.load(f)["skills"]

    groups = {}
    for name, entry in supports.items():
        key = f"{entry['icon']}_{entry['tier_roman'].lower()}"
        groups.setdefault(key, []).append((name, entry["tier_roman"]))
    shared = {k: v for k, v in groups.items() if len(v) > 1}

    cross_skill_only = []
    same_skill = []
    for key, members in sorted(shared.items()):
        rolled_strings = {f"{name} {tier}": name for name, tier in members}
        colliding_skills = []
        for skill, info in skills.items():
            possible = set(info.get("PossibleSupports", []))
            present = [name for s, name in rolled_strings.items() if s in possible]
            if len(present) > 1:
                colliding_skills.append((skill, present))
        if colliding_skills:
            same_skill.append((key, members, colliding_skills))
        else:
            cross_skill_only.append((key, members))

    lines = []
    lines.append("# Ambiguous support icons")
    lines.append("")
    lines.append("Regenerated by `tools/generate_support_collision_report.py` from")
    lines.append("`definitions/supports.json` + `definitions/supports_by_skills.json`.")
    lines.append("Don't hand-edit the tables below; re-run the script instead.")
    lines.append("")
    lines.append("## All icon+tier collisions")
    lines.append("")
    lines.append("| Icon (tier) | Colliding supports |")
    lines.append("|---|---|")
    for key, members in sorted(shared.items()):
        member_names = [name for name, _tier in members]
        names = " / ".join(member_names[:6])
        if len(member_names) > 6:
            names += f", +{len(member_names) - 6} more"
        lines.append(f"| `{key}` | {names} |")
    lines.append("")
    lines.append("## Collisions within a single skill")
    lines.append("")
    lines.append('These are the ones that actually print as "X or Y" in a warrant --')
    lines.append("a skill offers two or more of the colliding names at once, so no")
    lines.append("image-based method can resolve them further.")
    lines.append("")
    lines.append("| Icon (tier) | Colliding supports | Skills where it collides |")
    lines.append("|---|---|---|")
    for key, members, colliding_skills in same_skill:
        names = " / ".join(name for name, _tier in members)
        skill_names = sorted({s for s, _present in colliding_skills})
        skill_col = ", ".join(skill_names[:3])
        if len(skill_names) > 3:
            skill_col += f", +{len(skill_names) - 3} more"
        lines.append(f"| `{key}` | {names} | {skill_col} |")
    lines.append("")

    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"Wrote {OUTPUT_PATH}")
    print(f"{len(shared)} shared (icon, tier) groups: {len(same_skill)} real same-skill "
          f"collisions, {len(cross_skill_only)} cross-skill-only")


if __name__ == "__main__":
    generate()
